//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerSide
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfficeProducts
    {
        public int IdProduct { get; set; }
        public decimal Cost { get; set; }
        public int CountProduct { get; set; }
        public string Product { get; set; }
        public int Office { get; set; }
    
        public virtual Offices Offices { get; set; }
        public virtual Products Products { get; set; }
    }
}
