//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFLibrary
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    
    public partial class Offices
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Offices()
        {
            this.OfficeProducts = new HashSet<OfficeProducts>();
        }
    
        public int IdOffice { get; set; }
        public string Adress { get; set; }
        public string OrgName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfficeProducts> OfficeProducts { get; set; }
        public virtual Orgs Orgs { get; set; }

        public Offices(string address, string orgName)
        {
            Adress = address;
            OrgName = orgName;
            OfficeProducts = new HashSet<OfficeProducts>();
        }

        public void AddProducts(IQueryable<OfficeProducts> officeProducts)
        {
            foreach (OfficeProducts product in officeProducts)
            {
                OfficeProducts newProduct = new OfficeProducts(product, IdOffice);

                OfficeProducts.Add(newProduct);
            }
        }
    }
}
